# Generated by Django 4.2.1 on 2023-07-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_user_alter_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
